services:
  app:
    image: ghcr.io/jonahisadev/punch:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
