services:
  app:
    image: ghcr.io/jonahisadev/punch:latest
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
      PORT: 3000
    volumes:
      - /etc/enigma/token:/etc/enigma/token:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
