name: 🚀 Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "Run CI"
    uses: ./.github/workflows/ci.yml

  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jonahisadev'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHCR_PASS }}

      - name: Build the project
        run: yarn build

      - name: Log into Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jonahisadev/punch:latest
            ghcr.io/jonahisadev/punch:${{ github.sha }}

      - name: Create env
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker stack deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: ${{ vars.SWARM_STACK }}
          file: docker-compose.yml
          host: ${{ vars.SSH_HOST }}
          user: ${{ vars.SSH_USER }}
          ssh_key: ${{ secrets.SSH_DEPLOY_KEY }}
          env_file: ./envfile
          resolve_image: 'always'
          registry_host: 'ghcr.io'
          registry_user: ${{ secrets.GHCR_USER }}
          registry_pass: ${{ secrets.GHCR_PASS }}
          detach: false
